### ISSUE TITLE
CMake exclude pattern inadvertently excludes useful directory

### ISSUE THREAD

**Issue by joshavant** [wo80/essentia#2]
As I was playing with this library, I noticed that, confusingly, `src/essentia/streaming/algorithms/*.h` files were not ending up in the build product's `include/*` output (e.g. `include/essentia/streaming/algorithms` does not exist after building + installing).

This line appears to be causing that:
https://github.com/wo80/essentia/blob/65f6e69344be1b0c4f1334cd759b5b0b0775ea7c/CMakeLists.txt#L157

Presumably, this line was intended to exclude `src/algorithms/*` and not `src/essentia/streaming/algorithms/*`.

`src/essentia/streaming/algorithms/` contains many important structures for this library, so it would be useful to tune this exclusion filter so it only excludes `src/algorithms/*`.

**Comment by wo80** [comment]
> Presumably, this line was intended to exclude `src/algorithms/*` and not `src/essentia/streaming/algorithms/*`.

Correct, I'll fix that!

**Comment by wo80** [comment]
Latest commit should fix the missing headers and also the directory structure (header files in `include/essentia/essentia`).
